const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
const FETCH_USERS_FAILED = "FETCH_USERS_FAILED";
const LOGIN_IN_REQUEST = "LOGIN_IN_REQUEST";
const LOGGED_IN_SUCCESS = "LOGGED_IN_SUCCESS";
const SET_SELECTED_USER = "SET_SELECTED_USER";

const USERS_ACTION_TYPES = {
    FETCH_USERS_REQUEST,
    FETCH_USERS_SUCCESS,
    FETCH_USERS_FAILED,
    LOGIN_IN_REQUEST,
    LOGGED_IN_SUCCESS,
    SET_SELECTED_USER
}

export default USERS_ACTION_TYPES;